server:
  port: 3000
  servlet:
    context-path: /api

spring:
  h2:
    console:
      enabled: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost:9092/~/test
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    generate-ddl: false
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate
      use-new-id-generator-mappings: false
    properties:
      hibernate.format_sql: true
      hibernate.use_sql_comments: true

logging:
  level:
    root: info
    org.springframework.web.client: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: trace